plugins {
    id 'net.fabricmc.fabric-loom' version '1.15.5' apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

def getAppVersion = { ->
    try {
        def tag = providers.exec {
            commandLine 'git', 'tag', '--points-at', 'HEAD'
        }.standardOutput.asText.get().trim()
        if (tag.isEmpty()) {
            return rootProject.minecraft_version + "-SNAPSHOT"
        }
        return tag
    } catch (Exception e) {
        println "Warning: ${e.message}, is git installed?"
        return rootProject.minecraft_version + "-DEV"
    }
} as Object

allprojects {
    version = getAppVersion()
}