# Project
version=1.0.0
group=net.conczin
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Immersive Melodies
mod_author=Luke100000
mod_id=immersive_melodies
mod_homepage=https://conczin.net/
mod_sources=https://github.com/Luke100000/ImmersiveMelodies
mod_issues=https://github.com/Luke100000/ImmersiveMelodies/issues
license=GPL-3.0
description=Play custom melodies on various instruments and annoy your friends!
credits=""
minecraft_version_range=[1.21, 1.22)
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Fabric
fabric_version=0.116.3+1.21.1
fabric_loader_version=0.16.9
sodium_version=mc1.21.1-0.6.13-fabric
iris_version=1.8.8+1.21.1-fabric
indium_version=1.0.35+mc1.21
ferritecore_version=7.0.2-hotfix-fabric

# NeoForge
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
neoforge_version=21.1.197
neoforge_loader_version_range=[1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
